**Importing from CSV file **

In [23]:
pwd #to check where you are working

'C:\\Users\\Shailu'

In [24]:
#use cd to change directory location if needed

In [25]:
import pandas as pd #import pandas first
import numpy as np #import numpy

In [26]:
df=pd.read_csv("mercedesbenz.csv")

In [27]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [28]:
type(df)

pandas.core.frame.DataFrame

In [29]:
#use inbuilt functions

In [30]:
df.values

array([[0, 130.81, 'k', ..., 0, 0, 0],
       [6, 88.53, 'k', ..., 0, 0, 0],
       [7, 76.26, 'az', ..., 0, 0, 0],
       ...,
       [8412, 109.22, 'ak', ..., 0, 0, 0],
       [8415, 87.48, 'al', ..., 0, 0, 0],
       [8417, 110.85, 'z', ..., 0, 0, 0]], dtype=object)

In [31]:
df.value_counts()

ID    y       X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  X12  X13  X14  X15  X16  X17  X18  X19  X20  X21  X22  X23  X24  X26  X27  X28  X29  X30  X31  X32  X33  X34  X35  X36  X37  X38  X39  X40  X41  X42  X43  X44  X45  X46  X47  X48  X49  X50  X51  X52  X53  X54  X55  X56  X57  X58  X59  X60  X61  X62  X63  X64  X65  X66  X67  X68  X69  X70  X71  X73  X74  X75  X76  X77  X78  X79  X80  X81  X82  X83  X84  X85  X86  X87  X88  X89  X90  X91  X92  X93  X94  X95  X96  X97  X98  X99  X100  X101  X102  X103  X104  X105  X106  X107  X108  X109  X110  X111  X112  X113  X114  X115  X116  X117  X118  X119  X120  X122  X123  X124  X125  X126  X127  X128  X129  X130  X131  X132  X133  X134  X135  X136  X137  X138  X139  X140  X141  X142  X143  X144  X145  X146  X147  X148  X150  X151  X152  X153  X154  X155  X156  X157  X158  X159  X160  X161  X162  X163  X164  X165  X166  X167  X168  X169  X170  X171  X172  X173  X174  X175  X176  X177  X178  X179  X180  X181  X182  X183  X184  X185  X186  X187  X189  X190  X191  X192  X194  X195  X196  X197  X198  X199  X200  X201  X202  X203  X204  X205  X206  X207  X208  X209  X210  X211  X212  X213  X214  X215  X216  X217  X218  X219  X220  X221  X222  X223  X224  X225  X226  X227  X228  X229  X230  X231  X232  X233  X234  X235  X236  X237  X238  X239  X240  X241  X242  X243  X244  X245  X246  X247  X248  X249  X250  X251  X252  X253  X254  X255  X256  X257  X258  X259  X260  X261  X262  X263  X264  X265  X266  X267  X268  X269  X270  X271  X272  X273  X274  X275  X276  X277  X278  X279  X280  X281  X282  X283  X284  X285  X286  X287  X288  X289  X290  X291  X292  X293  X294  X295  X296  X297  X298  X299  X300  X301  X302  X304  X305  X306  X307  X308  X309  X310  X311  X312  X313  X314  X315  X316  X317  X318  X319  X320  X321  X322  X323  X324  X325  X326  X327  X328  X329  X330  X331  X332  X333  X334  X335  X336  X337  X338  X339  X340  X341  X342  X343  X344  X345  X346  X347  X348  X349  X350  X351  X352  X353  X354  X355  X356  X357  X358  X359  X360  X361  X362  X363  X364  X365  X366  X367  X368  X369  X370  X371  X372  X373  X374  X375  X376  X377  X378  X379  X380  X382  X383  X384  X385
8417  110.85  z   r   ae  c   d   aa  g   w   0    0    0    0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    0    1    0    0    0    0    0    0    1    0    0    1    0    0    1    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    1    0    1     1     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     1     1     0     0     0     0     0     1     1     0     0     0     1     0     0     0     1     1     0     0     0     0     1     0     1     0     0     0     0     1     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     1     0     0     0     0     0     1     0     1     0     0     0     0     1     0     0     0     0     0     1     1     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0       1
2794  93.57   o   l   as  f   d   ac  d   a   0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    1    0    1    0    1     1     0     1     0     0     1     0     0     0     0     1     0     0     0     0     0     0     1     1     1     0     0     0     0     0     1     1     0     0     0     1     0     0     0     1     0     0     0     0     0     1     0     1     0     0     0     0     1     0     1     0     1     0     0     1     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     1     0     1     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     1     1     0     1     0     0     1     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     1     0     0     0     1     1     0     1     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0       1
2791  114.83  ap  l   s   c   d   ac  j   h   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    1    0    1    0    0    0    0    0    0    0    0    1    0    1    1    1    1    1    0    0    0    0    0    1    0    0    0    0    0    0    0    1    0    1    0    1    1    0    1    1    0    0    0    0    0    0    0    0    1    1    0    0    0    0    0    0    0    0    0    0    1    0    0    0    0     0     0     0     0     0     0     0     0     0     0     0     0     1     1     0     0     0     1     1     0     0     0     0     0     1     0     0     1     1     0     0     0     1     0     1     1     0     0     0     0     1     0     0     0     0     1     0     1     0     0     0     1     1     0     1     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     1     1     0     0     0     0     0     0     1     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     1     0     0     1     0     0     0     0     0     0     0     0     0     1     0     0     0     1     1     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     1     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     1     1     0     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     1     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     1     0     0     1     0     1     1     0     1     0     0     0     0     1     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0       1
2790  88.55   t   b   m   a   d   ac  g   f   0    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    1    0    0    0    1    0    0    0    1    0    1    0    0    0    0    0    0    0    1    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    1    0    0     1     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     1     1     0     0     0     0     0     1     1     0     0     0     0     1     0     0     1     0     0     1     0     0     1     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     1     0     0     0     0     1     0     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     1     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     1     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     1     0     0     0     0     1     1     1     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0       1
2788  108.57  c   f   aq  d   d   ac  a   i   0    0    0    0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    1    1    0    0    0    0    0    0    1    0    0    1    0    0    0    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    1    0    1     1     0     1     0     0     0     0     0     0     0     1     0     0     1     0     0     0     1     1     1     0     0     0     0     0     0     1     0     0     0     1     0     0     0     1     1     0     0     0     0     1     0     1     0     0     0     1     1     0     0     0     0     0     0     1     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     1     0     1     0     0     0     0     0     0     0     0     1     0     0     0     1     0     0     0     1     0     1     0     0     0     0     0     0     0     0     1     1     0     1     0     1     0     0     0     1     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     1     0     1     0     0     0     0     1     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     1     1     0     0     0     0     0     1     1     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0       1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ..
5611  75.41   az  v   n   f   d   p   j   f   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    1    1    0    1    0    0    0    1    0    1    0    0    0    0    0    1    0    0    1    0    0    0    0    0    0    0    1    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    1    0    0    1    0    1    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    1    0    0     1     0     0     0     0     0     0     1     0     0     1     0     0     1     0     0     0     0     0     1     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     1     1     0     0     0     0     0     0     1     1     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     1     0     1     0     0     1     0     0     0     0     0     1     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     1     0     0     1     0     0     1     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     0     1     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0       1
5606  109.37  ak  l   as  f   d   p   d   a   0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0    1    0    1    0    1     1     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     1     1     1     0     0     0     0     0     0     1     0     0     0     1     0     0     0     1     0     0     0     0     0     1     0     1     0     0     0     0     1     1     0     0     1     0     1     0     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     1     0     1     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     1     1     0     0     0     0     1     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     1     0     0     0     0     1     0     0     0     0     0     0     0     0     0     1     0     1     0     1     0     0     0     0     0     0     0     1     0     1     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     1     0     0     0     0     0     0     1     0     0     1     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0     1     0     1     1     0     0     0     0     0     0     1     0     0     1     0     1     0     0     0     0     0     0     0     0     0     0     1     0     0     0     0     0     0     0     0     0     0       1

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [33]:
df.describe() #removes all the character elements

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [34]:
df=pd.read_csv("test1.csv") #to change seperator use pd.read_csv("eg.csv",sep="x")

In [35]:
df.head()

  Unnamed: 0  c1  c2  c3  c4
0       row1   0   1   2   3
1       row2   4   5   6   7
2       row3   8   9  10  11
3       row4  12  13  14  15
4       row5  16  17  18  19

In [36]:
df.iloc[:,:3]

  Unnamed: 0  c1  c2
0       row1   0   1
1       row2   4   5
2       row3   8   9
3       row4  12  13
4       row5  16  17

In [37]:
df=pd.read_csv("test1.csv", usecols=["c1","c3"]) #usecols function to chip away necessary columns

In [38]:
df.head()

   c1  c3
0   0   2
1   4   6
2   8  10
3  12  14
4  16  18

In [39]:
df.describe()

              c1         c3
count   5.000000   5.000000
mean    8.000000  10.000000
std     6.324555   6.324555
min     0.000000   2.000000
25%     4.000000   6.000000
50%     8.000000  10.000000
75%    12.000000  14.000000
max    16.000000  18.000000

In [52]:
from io import StringIO #StringIO is not working here

In [61]:
data=("index,a,b,c\n","apple,orange,8,9\n","1,2,3,4")

In [62]:
df=pd.read_csv(StringIO(data))

TypeError: initial_value must be str or None, not tuple

***READING JSON, HTML, PICKEL AND EXCEL FILES ***

In [63]:
#json is a combination of key value pairs

In [74]:
Data ={"employee name":"shy","email":"sxcc","jobprofile":"science"}

In [73]:
pd.read_json(Data)

ValueError: Invalid file path or buffer object type: <class 'dict'>